Collections:
- Name: fp16
  Metadata:
    Training Data:
    - Cityscapes
  Paper:
    URL: https://arxiv.org/abs/1710.03740
    Title: Mixed Precision Training
  README: configs/fp16/README.md
  Code:
    URL: https://github.com/open-mmlab/mmcv/blob/v1.3.14/mmcv/runner/hooks/optimizer.py#L134
    Version: v1.3.14
  Converted From:
    Code: https://github.com/baidu-research/DeepBench
Models:
- Name: fcn_r101-d8_512x1024_80k_fp16_cityscapes
  In Collection: fp16
  Metadata:
    backbone: R-101-D8
    crop size: (512,1024)
    lr schd: 80000
    inference time (ms/im):
    - value: 115.74
      hardware: V100
      backend: PyTorch
      batch size: 1
      mode: FP32
      resolution: (512,1024)
    memory (GB): 5.37
  Results:
  - Task: Semantic Segmentation
    Dataset: Cityscapes
    Metrics:
      mIoU: 76.8
  Config: configs/fp16/fcn_r101-d8_512x1024_80k_fp16_cityscapes.py
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/fp16/fcn_r101-d8_512x1024_80k_fp16_cityscapes/fcn_r101-d8_512x1024_80k_fp16_cityscapes_20200717_230921-50245227.pth
- Name: pspnet_r101-d8_512x1024_80k_fp16_cityscapes
  In Collection: fp16
  Metadata:
    backbone: R-101-D8
    crop size: (512,1024)
    lr schd: 80000
    inference time (ms/im):
    - value: 114.03
      hardware: V100
      backend: PyTorch
      batch size: 1
      mode: FP32
      resolution: (512,1024)
    memory (GB): 5.34
  Results:
  - Task: Semantic Segmentation
    Dataset: Cityscapes
    Metrics:
      mIoU: 79.46
  Config: configs/fp16/pspnet_r101-d8_512x1024_80k_fp16_cityscapes.py
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/fp16/pspnet_r101-d8_512x1024_80k_fp16_cityscapes/pspnet_r101-d8_512x1024_80k_fp16_cityscapes_20200717_230919-ade37931.pth
- Name: deeplabv3_r101-d8_512x1024_80k_fp16_cityscapes
  In Collection: fp16
  Metadata:
    backbone: R-101-D8
    crop size: (512,1024)
    lr schd: 80000
    inference time (ms/im):
    - value: 259.07
      hardware: V100
      backend: PyTorch
      batch size: 1
      mode: FP32
      resolution: (512,1024)
    memory (GB): 5.75
  Results:
  - Task: Semantic Segmentation
    Dataset: Cityscapes
    Metrics:
      mIoU: 80.48
  Config: configs/fp16/deeplabv3_r101-d8_512x1024_80k_fp16_cityscapes.py
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/fp16/deeplabv3_r101-d8_512x1024_80k_fp16_cityscapes/deeplabv3_r101-d8_512x1024_80k_fp16_cityscapes_20200717_230920-bc86dc84.pth
- Name: deeplabv3plus_r101-d8_512x1024_80k_fp16_cityscapes
  In Collection: fp16
  Metadata:
    backbone: R-101-D8
    crop size: (512,1024)
    lr schd: 80000
    inference time (ms/im):
    - value: 127.06
      hardware: V100
      backend: PyTorch
      batch size: 1
      mode: FP32
      resolution: (512,1024)
    memory (GB): 6.35
  Results:
  - Task: Semantic Segmentation
    Dataset: Cityscapes
    Metrics:
      mIoU: 80.46
  Config: configs/fp16/deeplabv3plus_r101-d8_512x1024_80k_fp16_cityscapes.py
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/fp16/deeplabv3plus_r101-d8_512x1024_80k_fp16_cityscapes/deeplabv3plus_r101-d8_512x1024_80k_fp16_cityscapes_20200717_230920-cc58bc8d.pth
